console.log("Hi there!")
wait(5000)
console.log("Are you here?")
wait(5000)
console.log("Am I talking to myself?")
wait(5000)
console.log("ARE YOU HERE???!!???")
wait(5000)
console.log("I think you're here")
wait(1000)
console.log("So do you know the best gift?")
wait(10000)
console.log("YOUR IP")
location.href="https://whatismyipaddress.com/"
wait(5000)
console.log("Is this a good gift?")
